server:
  port: 8080
  error:
    include-exception: true     # ??? exception? ??? ???? ??
    path: '/error'               # ??? ??? Handler? ??
    whitelabel:
      enabled: true             # ?? ?? ??? ????? ??? ?? ??? ?? ??


spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  datasource: # DATABASE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NM}
    password: ${DB_PW}

  jpa: # JPA
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            redirect-uri: ${kakao.client.redirect-uri}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client_name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: ${kakao.token-url}
            user-info-uri: ${kakao.user-info-url}
            user-name-attribute: id

api_prefix: /api

kakao:
  token-url: ${KAKAO_TOKEN_URL}
  user-info-url: ${KAKAO_USER_INFO_URL}

  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}

file:
  upload-dir: src/main/resources/static/images/