server:
  port: 8080
  error:
    include-exception: true     # ??? exception? ??? ???? ??
    path: '/error'               # ??? ??? Handler? ??
    whitelabel:
      enabled: true             # ?? ?? ??? ????? ??? ?? ??? ?? ??


spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  datasource: # DATABASE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NM}
    password: ${DB_PW}

  jpa: # JPA
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e745d2784bcc5ccea601fe44bf8b4b67
            redirect-uri: http://localhost:8080/api/oauth2/kakao
            client-secret: 9E4eAl71bFByhI0PLd9BIWxDIeIAKnkx
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client_name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

api_prefix: /api

file:
  upload-dir: src/main/resources/static/images/